title:        deepdish
tagline:      'Deep learning at the University of Chicago'
description:  'Serving Up Chicago-Style Deep Learning.'
url:          http://deepdish.io/
baseurl:      ''
author:
  name:       ''
  email:      ''
markdown:     redcarpet
permalink:    pretty
redcarpet:
      extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:  pygments
paginate:     3
authors:
  gustav:
    name: Gustav Larsson
    display_name: Gustav
    email: gustav@deepdish.io
    github: gustavla
  mark:
    name: Mark Stoehr
    display_name: Mark
    email: mark@deepdish.io
    github: markstoehr

  
