title:        deepdish
tagline:      'Deep learning at the University of Chicago'
description:  'Serving Up Chicago-Style Deep Learning.'
url:          http://deepdish.io/
baseurl:      ''
author:
  name:       ''
  email:      ''
markdown:     kramdown
permalink:    pretty
highlighter:  pygments
paginate:     5
