title:        deepdish
tagline:      'Deep learning at the University of Chicago'
description:  'Deep learning blog and reference implementations.'
url:          https://amitgroup.github.io/deepdish
author:
  name:       ''
  email:      ''
markdown:     kramdown
permalink:    pretty
highlighter:  pygments
paginate:     5
