title:        deepdish
tagline:      'Deep learning at the University of Chicago'
description:  'Deep learning blog and reference implementations.'
url:          http://deepdish.io/
baseurl:      ''
author:
  name:       ''
  email:      ''
markdown:     redcarpet
permalink:    pretty
highlighter:  pygments
paginate:     5
